name: Azure Publish

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  publish-app:
    name: Publish App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SPACETIMESERVER_AZURE_CREDENTIALS }}

      - name: Deploy App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: SpaceTime-Server/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.SPACETIMESERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPACETIMESERVER_REGISTRY_PASSWORD }}
          containerAppName: spacetime-server
          resourceGroup: SpaceTime-Server
          imageToBuild: spacetimee/spacetime-server:${{ github.sha }}